#!/usr/bin/env ruby

require 'yaml'

y = YAML.load(File.open("haskell.yml").read())
y.each_with_index do |prog, pi|
	nam = prog['nam']
	src = prog['src']
	exp = prog['exp']
	fn_hs  = "%03d_#{nam}.hs" % pi
	fn_exp = "%03d_#{nam}.exp" % pi

	print "Generating #{fn_hs}, #{fn_exp}\n"
	File.open(fn_hs,  "w") { |f| f.write(src) }
	File.open(fn_exp, "w") { |f| f.write(exp) }
end

mk = <<MK
HS=$(wildcard *.hs)
O=$(HS:.hs=.o)
all: $O
%.o: %.hs
	ghci < $< 2>&1 | egrep -v '(version|Loading|Leaving)' > $@; diff -u $(basename $<).exp $@
clean:
	rm -rf *.hs makefile *.o *.exp
MK
f = File.open("makefile", "w") { |f| f.write(mk) }

system('make')
